version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: helianthus
      POSTGRES_PASSWORD: helianthus
      POSTGRES_DB: helianthus
    ports:
      - "5432:5432"